services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_local
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html
      - ./private_html:/var/www/private_html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: crowdilm
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: P@ssw0rd
